version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: taxspeedy-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: taxspeedy
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: